# Site settings
title: Página do Dimas
email: dimasad@ufmg.br
description: "Notas de aula e laboratório"
baseurl: ""
url: "http://dimasad.github.io"
show_downloads: false
google_analytics: false
theme: jekyll-theme-slate

collections:
  mecvoo:
    output: true
  eletronica:
    output: true


# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  syntax_highlighter_opts:
    default_lang: c++
